# Generated by Django 5.2.7 on 2025-10-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='userquestionselect',
            old_name='choice',
            new_name='select',
        ),
    ]
