# Generated by Django 5.2.7 on 2025-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0002_rename_test_question_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=100, verbose_name='テスト名'),
        ),
    ]
