# Generated by Django 5.2.7 on 2025-10-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0003_alter_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, verbose_name='解答の解説'),
        ),
    ]
