# Generated by Django 5.2.7 on 2025-10-21 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0004_alter_question_answer_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertestresult',
            options={'ordering': ('-count', '-submitted')},
        ),
        migrations.RenameField(
            model_name='usertestresult',
            old_name='test',
            new_name='exam',
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='count',
            field=models.IntegerField(default=0, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='userquestionselect',
            name='correct',
            field=models.BooleanField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userquestionselect',
            name='select',
            field=models.IntegerField(verbose_name='解答'),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='点数'),
        ),
        migrations.AlterUniqueTogether(
            name='usertestresult',
            unique_together={('user', 'exam', 'count')},
        ),
    ]
