# Generated by Django 5.2.7 on 2025-11-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0006_rename_user_userquestionselect_test_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='grade',
            field=models.CharField(choices=[('elementary', '小学生'), ('junior', '中学生'), ('high', '高校生')], default='elementary', max_length=20, verbose_name='学年区分'),
        ),
    ]
