# Generated by Django 5.2.7 on 2026-01-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymath', '0008_alter_question_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='問題番号'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'number'), name='unique_exam_question_number'),
        ),
    ]
